### PR TITLE
bump version to 0.7.0

### PR DESCRIPTION
**Pull request by stoeffel**

### CODE REVIEW

**Comment by BrianHicks** [comment]
We’ve just been using the minor version, could we stay with that convention?

**Comment by stoeffel** [comment]
> We’ve just been using the minor version, could we stay with that convention?

I'm cool with that, but I wonder what the reason behind that convention is.

**Comment by BrianHicks** [comment]
Adding a new checklist item seems more like a feature-level change than a patch-level change to me. I definitely could have phrased that initial comment better.

If you disagree strongly, feel free to just merge

**Comment by stoeffel** [comment]
@BrianHicks changed.

**Pull request merged**
